//! Example: Apply a diff patch to a base XML document
//!
//! This example demonstrates how to apply a diff (generated by the diff command)
//! to a base document to reconstruct the modified version.
//!
//! Usage: cargo run --example patch <base.xml> <diff.xml>

use std::env;
use std::io;
use xml_3dm::{BaseNodeFactory, Patch, XmlParser};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let args: Vec<String> = env::args().collect();

    if args.len() != 3 {
        eprintln!("Usage: {} <base.xml> <diff.xml>", args[0]);
        std::process::exit(1);
    }

    let base_file = &args[1];
    let diff_file = &args[2];

    // Parse base and diff
    let parser = XmlParser::new(BaseNodeFactory);

    eprintln!("Parsing base: {}", base_file);
    let base = parser.parse_file(base_file)?;

    eprintln!("Parsing diff: {}", diff_file);
    let diff = parser.parse_file(diff_file)?;

    // Apply patch
    eprintln!("Applying patch...");
    let patcher = Patch::new();
    patcher.patch(&base, &diff, &mut io::stdout())?;

    eprintln!("\nPatch applied successfully!");
    Ok(())
}
